{
 "title": "Python Copy",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "gauge",
   "description": "CPU Usage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_percent{endpoint=\"metric\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Status",
   "type": "gauge",
   "description": "Memory Status",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memory_used{instance=\"10.0.84.108:9918\"}",
     "legendFormat": "Used Memory"
    },
    {
     "expr": "memory_free{instance=\"10.0.84.108:9918\"}",
     "legendFormat": "Free Memory"
    },
    {
     "expr": "total_memory{instance=\"10.0.84.108:9918\"}",
     "legendFormat": "Total Memory"
    }
   ]
  },
  {
   "title": "File Systems Status",
   "type": "piechart",
   "description": "File Systems Status",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=~\"disk_free_percent.*\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "py_os_version_info{instance=\"10.0.84.108:9918\"}",
     "legendFormat": "{{version}}"
    }
   ]
  }
 ]
}