{
 "title": "Python-ext",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "UP",
   "type": "stat",
   "description": "UP",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"py-extservice\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "description": "CPU Usage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_usage_percent{job=\"py-extservice\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Status",
   "type": "gauge",
   "description": "Memory Status",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memory_total_bytes{job=\"py-extservice\"}",
     "legendFormat": "Total Memory"
    },
    {
     "expr": "memory_used_bytes{job=\"py-extservice\"}",
     "legendFormat": "Used Memory"
    },
    {
     "expr": "memory_free_bytes{job=\"py-extservice\"}",
     "legendFormat": "Free Memory"
    }
   ]
  },
  {
   "title": "Total Disk Space",
   "type": "barchart",
   "description": "Total Disk Space",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "disk_total_bytes{job=\"py-extservice\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Free Disk Space",
   "type": "barchart",
   "description": "Free Disk Space",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "disk_free_bytes{job=\"py-extservice\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  }
 ]
}